
if ~exist('../private','dir')
  mkdir('../private');
end

mex -O -DFEATURE=nproc  CFLAGS="-fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src ../../cpuinfo/src/cpuinfo.c mxCpuinfo.c ...
  -outdir ../private -output mxNProc
mex -O -DFEATURE=mmx    CFLAGS="-fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src ../../cpuinfo/src/cpuinfo.c mxCpuinfo.c ...
  -outdir ../private -output mxHasMmx
mex -O -DFEATURE=sse    CFLAGS="-fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src ../../cpuinfo/src/cpuinfo.c mxCpuinfo.c ...
  -outdir ../private -output mxHasSse
mex -O -DFEATURE=sse2   CFLAGS="-fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src ../../cpuinfo/src/cpuinfo.c mxCpuinfo.c ...
  -outdir ../private -output mxHasSse2
mex -O -DFEATURE=sse3   CFLAGS="-fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src ../../cpuinfo/src/cpuinfo.c mxCpuinfo.c ...
  -outdir ../private -output mxHasSse3
mex -O -DFEATURE=ssse3  CFLAGS="-fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src ../../cpuinfo/src/cpuinfo.c mxCpuinfo.c ...
  -outdir ../private -output mxHasSsse3
mex -O -DFEATURE=sse41  CFLAGS="-fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src ../../cpuinfo/src/cpuinfo.c mxCpuinfo.c ...
  -outdir ../private -output mxHasSse41
mex -O -DFEATURE=sse42  CFLAGS="-fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src ../../cpuinfo/src/cpuinfo.c mxCpuinfo.c ...
  -outdir ../private -output mxHasSse42
mex -O -DFEATURE=popcnt CFLAGS="-fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src ../../cpuinfo/src/cpuinfo.c mxCpuinfo.c ...
  -outdir ../private -output mxHasPopcnt
mex -O -DFEATURE=avx    CFLAGS="-fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src ../../cpuinfo/src/cpuinfo.c mxCpuinfo.c ...
  -outdir ../private -output mxHasAvx
