%-----------------------------------------------------------------------------
% File    : compileMex.m
% Contents: build MEX-files
%           NB: This file is obsolete. Use the makefile instead.
% Author  : Kristian Loewe
%-----------------------------------------------------------------------------

if ~exist('../private','dir'); mkdir('../private'); end

%% corecnt
mex -O -DFEATURE=ncores ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src mxCpuinfo.c ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private -output mxCorecnt

%% proccnt
mex -O -DFEATURE=nproc ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src mxCpuinfo.c ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private -output mxProccnt

%% mmx
mex -O -DFEATURE=mmx ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src mxCpuinfo.c ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private -output mxHasMmx

%% sse
mex -O -DFEATURE=sse ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src mxCpuinfo.c ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private -output mxHasSse

%% sse2
mex -O -DFEATURE=sse2 ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src mxCpuinfo.c ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private -output mxHasSse2

%% sse3
mex -O -DFEATURE=sse3 ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src mxCpuinfo.c ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private -output mxHasSse3

%% ssse3
mex -O -DFEATURE=ssse3 ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src mxCpuinfo.c ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private -output mxHasSsse3

%% sse4.1
mex -O -DFEATURE=sse41 ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src mxCpuinfo.c ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private -output mxHasSse41

%% sse4.2
mex -O -DFEATURE=sse42 ...
CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src mxCpuinfo.c ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private -output mxHasSse42

%% popcnt
mex -O -DFEATURE=popcnt ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src mxCpuinfo.c ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private -output mxHasPopcnt

%% avx
mex -O -DFEATURE=avx ...
  CFLAGS="-Wall -Wextra -Wno-unused-parameter -Wconversion -pedantic ...
  -fPIC -std=c99 -march=native" ...
  -I../../cpuinfo/src mxCpuinfo.c ../../cpuinfo/src/cpuinfo.c ...
  -outdir ../private -output mxHasAvx
